name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write # Required for OIDC support, though not strictly for this specific action, it's good practice for GH Pages workflows
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x' # Or your specific Ruby version, e.g., '3.2'
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler jekyll
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: List _site contents
        run: ls -la _site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: anditherobot.github.io # Replace with your custom domain if you have one, otherwise remove this line
